### ISSUE TITLE
BEP: invalid revision 2 (! = 1) in loaded driver

### ISSUE THREAD

**Issue by DeusHyper** [ananjaser1211/Opencore-HP-Pavilion-Gaming-15-cx0056wm#11]
Hey,

I am very new to the hackintosh scene and I wanted to try this on my Laptop. The only problem is that I have an HP Pavilion Gaming 15 cx0xxx, which is same spec except that I built in 16 gb crucial ram, also I have just an 128gb ssd and 1tb hdd and the rtl8822BE PCIe adapter. everything else should be same spec. What do I have to do to get this running?
Thanks in advance

best regards,
Jonas

**Comment by SkyrilHD** [comment]
Your config is broken. Since you did not attach any useful file/info, I cannot help you. Sorry. Re-do your EFI and follow the [guide](https://dortania.github.io/OpenCore-Install-Guide/) by dortania.
