### ISSUE TITLE
I install dis and laptop no macbuak pro

### ISSUE THREAD

**Issue by Dyneteve** [ananjaser1211/Opencore-HP-Pavilion-Gaming-15-cx0056wm#13]
I dis instalz thiz and lapfoz jotz toufhbarz pro wherez toufhbarz and toufhsars and speakerzaes

Very Bhai bad software

**Comment by ananjaser1211** [comment]
no volte ims support :(

**Comment by Dyneteve** [comment]
> no volte ims support :(

Where vONR sir snapdragonul modem ifon sdx no cellular what
