### ISSUE TITLE
crsutil unkown SIP status

### ISSUE THREAD

**Issue by freakyappleman** [ananjaser1211/Opencore-HP-Pavilion-Gaming-15-cx0056wm#19]
I have run the crsutil status command on the terminal and the following output was shown:

```
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: disabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```
Can I re-enable SIP with the current efi configuration or is there a reason why the SIP is set this way?

**Comment by SkyrilHD** [comment]
The easiest way to enable SIP is by resetting the NVRAM. Alternatively, you can enable SIP by booting to recovery and type the following command in the Terminal: `csrutil enable`
