### ISSUE TITLE
Is the Intel® Wireless-AC 9560 802.11b/g/n/ac worth buying?

### ISSUE THREAD

**Issue by freakyappleman** [ananjaser1211/Opencore-HP-Pavilion-Gaming-15-cx0056wm#7]
@SkyrilHD I am currently using an intel 8265 NGW and the speeds are just garbage, either on hackintosh or windows. My question is what speeds are you getting with the 9560, if it's possible to know? Does it enable airdrop as well? Thank you in advance.

**Comment by SkyrilHD** [comment]
I don't use the 9560, but I have a 7265 AC, which works very well. 2.4GHz has worse performance than 5GHz. With 5GHz, I get 250/12 (which is my speed) while on 2.4Ghz I barely get 50 down. AirDrop does not work on all Intel Wi-Fi cards. If you want Continuity features, you need to get a Broadcom card, which some are natively supported.

There is a buyers guide which will you help a lot: https://dortania.github.io/Wireless-Buyers-Guide/

**Comment by ananjaser1211** [comment]
> @SkyrilHD I am currently using an intel 8265 NGW and the speeds are just garbage, either on hackintosh or windows. My question is what speeds are you getting with the 9560, if it's possible to know? Does it enable airdrop as well? Thank you in advance.

I am using the AC9560 as it came with my computer basically, im maxing out my WiFi package just fine (~400MBPS down with ~80MBPS up) i am using 5GHz, i would test 2.4GHz but i recently had to clear hackintosh as i needed linux urgently and i was out of space on the NVME lol, but in the time ive used hackintosh the experience was near flawless, Especially with bluetooth as i am constantly using my bluetooth headset while using WiFi. 

perhaps the only thing odd ive noticed is that when the computer goes to sleep, my bluetooth device remains connected, which might be a sleep issue from my system, or something else in the bluetooth itself.

Airdrop did not work as i recall, it could see my iPhone but it would fail to connect.

overall it was very decent, if the chip fits your device i dont see why not.
